version: 2.1

orbs:
  haskell: haskell-works/haskell-build@4.0.5
  github: haskell-works/github-release@1.3.0
  hackage: haskell-works/hackage@1.2.0

executors:
  darwin:
    macos:
      xcode: 10.0

workflows:
  multiple-ghc-build:
    jobs:
      - haskell/build-with-binary-cache:
          name: GHC 8.6.5
          executor: haskell/ghc-8_6_5
          context: haskell-ci
          binary-cache-uri: ${BINARY_CACHE_URI-"http://hw-binary-cache-us-west-2-a.s3-website-us-west-2.amazonaws.com/archive"}
          cabal-build-extra: --write-ghc-environment-files=ghc8.4.4+
          cabal-test-extra: --test-show-details=direct

      - haskell/build-with-binary-cache:
          name: GHC 8.8.2
          executor: haskell/ghc-8_8_2
          context: haskell-ci
          binary-cache-uri: ${BINARY_CACHE_URI-"http://hw-binary-cache-us-west-2-a.s3-website-us-west-2.amazonaws.com/archive"}
          cabal-build-extra: --write-ghc-environment-files=ghc8.4.4+
          cabal-test-extra: --test-show-details=direct
          workspace-dir: workspace/ghc-8.8.2
          write-result-workspace: true

      - haskell/build-with-cci-cache:
          name: Darwin
          executor: darwin
          run-tests: false
          fail-incoherent-builds: false
          write-result-workspace: true
          workspace-dir: workspace/osx
          after-checkout:
            - restore_cache:
                keys:
                  - homebrew-itself-cache
            - run:
                name: Install GHC
                command: |
                  brew update
                  brew install jq md5sha1sum ghc cabal-install

            - save_cache:
                key: homebrew-itself-cache
                # I cache Homebrew itself, not the stuff that is installed with it
                # because brew update takes up to 4 minutes for some reason.
                paths: [/usr/local/Homebrew]

            - run:
                name: Install cabal-plan
                command: |
                  curl -L https://github.com/haskell-works/cabal-plan/releases/download/v0.5.0.0/cabal-plan_x86_osx.tar.gz -o cabal-plan_x86_osx.tar.gz
                  tar zxvf cabal-plan_x86_osx.tar.gz -C /usr/local/bin cabal-plan
                  rm cabal-plan_x86_osx.tar.gz
          filters:
            branches:
              only: master

      - github/release-cabal:
          context: haskell-ci
          name: GitHub Release
          attach-workspace: true
          requires:
            - GHC 8.6.5
            - GHC 8.8.2
            # - Darwin
          checkout: true
          before-release:
            - run:
                name: Prepare environment for release
                command: |
                  source ./workspace/ghc-8.6.5/project.env
                  tar zcvf /tmp/artefacts/${CIRCLE_PROJECT_REPONAME}_${BUILD_ARCH}_${BUILD_OS_NAME}.tar.gz -C ./workspace/ghc-8.6.5/dist/ ./${BUILD_EXE_NAME}

                  # source ./workspace/osx/project.env
                  # tar zcvf /tmp/artefacts/${CIRCLE_PROJECT_REPONAME}_${BUILD_ARCH}_${BUILD_OS_NAME}.tar.gz -C ./workspace/osx/dist/ ./${BUILD_EXE_NAME}
          filters:
            branches:
              only: master

      # - hackage/upload:
      #     context: haskell-ci
      #     publish: true
      #     requires:
      #       - GitHub Release
